"""init: usrs / usrs_info / videos

Revision ID: bd08d8cbe829
Revises: 
Create Date: 2026-09-16 02:33:31.511255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd08d8cbe829'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usrs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('passwd', sa.String(length=256), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('sess', sa.String(length=256), nullable=True),
    sa.Column('bak', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sess')
    )
    op.create_index(op.f('ix_usrs_id'), 'usrs', ['id'], unique=False)
    op.create_table('usrs_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('bak', sa.String(length=256), nullable=True),
    sa.Column('bak1', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('videos',
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=True),
    sa.Column('v_name', sa.String(length=256), nullable=True),
    sa.Column('info', sa.String(length=256), nullable=True),
    sa.Column('uper_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('like', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('vid'),
    sa.UniqueConstraint('vid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    op.drop_table('usrs_info')
    op.drop_index(op.f('ix_usrs_id'), table_name='usrs')
    op.drop_table('usrs')
    # ### end Alembic commands ###
