"""add sessions table, drop usrs.sess

Revision ID: e8b8deea3ba1
Revises: bd08d8cbe829
Create Date: 2026-09-16 03:42:17.227932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e8b8deea3ba1'
down_revision: Union[str, Sequence[str], None] = 'bd08d8cbe829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('exp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_sessions_exp'), 'sessions', ['exp'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.drop_index(op.f('sess'), table_name='usrs')
    op.drop_column('usrs', 'sess')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usrs', sa.Column('sess', mysql.VARCHAR(length=256), nullable=True))
    op.create_index(op.f('sess'), 'usrs', ['sess'], unique=True)
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_exp'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
